modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL=""
license="ARR"
[[mods]]
    modId="chipped_express"
    version="1.2.0"
    displayName="ChippedExpress"
    description=""

[[dependencies.chipped_express]]
	modId = "chipped"
	mandatory = true
	versionRange = "[1.0.0,)"
	ordering = "NONE"
	side = "BOTH"